// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  DB: D1Database,
  KV: KVNamespace,
  REDDIT_CLIENT_ID: string,
  REDDIT_CLIENT_SECRET: string,
  REDDIT_REDIRECT_URI: string
}
