name = "typing-monkeytype-integration"
compatibility_date = "2024-03-29"
compatibility_flags = ["nodejs_compat"]

[vars]
REDDIT_CLIENT_ID = "dMqeXSkJkJy2zrYY5NTWmw"
REDDIT_REDIRECT_URI = "https://typing-monkeytype-integration.pages.dev/api/auth/callback"

[[d1_databases]]
binding = "DB"
database_name = "typing-monkeytype-integration"
database_id = "423c0c11-3851-45c2-a9c5-eeb159c866b2"
